apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-cloud-kubernetes-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 2.12.1
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true