apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: platform
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    # Changelog at https://github.com/stakater/Reloader/releases
    targetRevision: 1.0.74
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true